id = "latte"
name = "Latte"
version = "0.1.0"
schema_version = 1
authors = ["Jasper Smet <zed-latte.auction571@simplelogin.com>"]
description = "Latte templating language support for Zed"
repository = "https://github.com/josbeir/zed-latte"

[grammars.latte]
repository = "https://github.com/josbeir/tree-sitter-latte"
commit = "b0e33254cb8fdedb7a36bd4ed548c3d43b53dcb5"

[grammars.php_only]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "b2278dbac9d58b02653fe6a8530ccebc492e4ed4"
path = "php_only"

[language_servers.emmet]
name = "Emmet Language Server"
language = "Latte"
