id = "latte"
name = "Latte"
version = "0.1.0"
schema_version = 1
authors = ["Jasper Smet <josbeir@gmail.com>"]
description = "Latte templating language support for Zed"
repository = "https://github.com/josbeir/zed-latte"

[grammars.latte]
repository = "https://github.com/josbeir/tree-sitter-latte"
commit = "6156647bf20c7af4d5823702fa4d67d05fb5de62"

[grammars.php_only]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "b2278dbac9d58b02653fe6a8530ccebc492e4ed4"
path = "php_only"

[language_servers.emmet]
name = "Emmet Language Server"
language = "Latte"

[language_servers.vscode-html-language-server]
name = "HTML Language Server"
language = "Latte"
