id = "latte"
name = "Latte"
version = "0.1.0"
schema_version = 1
authors = ["Jasper Smet <josbeir@gmail.com>"]
description = "Latte templating language support for Zed"
repository = "https://github.com/josbeir/zed-latte"

[grammars.latte]
repository = "file:///home/josbeir/Sites/tree-sitter-latte"
commit = "1f896246891f2d776ece669fd5049fc89587a9fe"

# [grammars.php_only]
# repository = "https://github.com/tree-sitter/tree-sitter-php"
# commit = "b2278dbac9d58b02653fe6a8530ccebc492e4ed4"
# path = "php_only"

# [language_servers.emmet]
# name = "Emmet Language Server"
# language = "Latte"

# [language_servers.intelephense]
# name = "Intelephense"
# language = "Latte"
# language_ids = { Latte = "latte" }

# [language_servers.phptools]
# name = "PhpTools"
# language = "Latte"
# language_ids = { Latte = "latte" }

# [language_servers.phpactor]
# name = "Phpactor"
# language = "Latte"
